name: Security test
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
    sast_scan:
        name: Run Bandit Scan
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.13.1", "3.13.2"]
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            
            - name: Install Bandit
              run: pip install bandit
            
            - name: Run Bandit Scan
              run: bandit -ll -ii -r . -f json -o bandit_report.json

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: bandit-findings
                path: bandit_report.json


    image_scan:
        name: Build Image and Run Image Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Docker
              uses: docker/setup-docker-action@370a7dad4b8ce8dbf00f9363e1652e5074dd6abe
              with:
                version: 27.4.0
            
            - name: Login to Docker Hub
              uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASS }}

            - name: Build Docker image
              run : docker build -f Dockerfile -t recipe:v.1 .
              
            - name: Docker Scout Scan
              uses: docker/scout-action@b23590dc1e4d09febc00cfcbc51e9e8c0f7ee9f3
              with:
                command: quickview, cves
                only-severities: critical, high, medium
                sarif-file: scout_report.sarif
                exit-code: true

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: docker-scout-findings
                path: scout_report.sarif
