name: Test&Lint

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13.2]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
    
    - name: Create .env file
      run: |
        touch .env
        echo '${{ secrets.ENV_VAR_SEC }}' >> .env
    
    - name: Create db/password file
      run: |
        echo '${{ secrets.DB_PASS }}' >> password.txt

    - name: Test with pytest
      run: docker compose run --rm api pytest

    - name: Lint with Flake8
      run: docker compose run --rm api flake8

      continue-on-error: true
